allowBuilds:
  '@parcel/watcher': true
  core-js: true
  dtrace-provider: true
  electron: true
  es5-ext: true
  esbuild: true
  fsevents: true
  husky-v4: true
  puppeteer: true
  spawn-sync: true
  unrs-resolver: true
